// GENERATED by engine/scripts/gen_swift_fixtures.py — do not edit.
// Regenerate after any intentional change to the Python reference.
@testable import NavCore

let dstarSteps: [([(Int32, Int32, Int)], Cell, Double)] = [([], Cell(-99, -99), 1.9196067811865478), ([(4, 7, 2), (4, 8, 2)], Cell(-99, -99), 2.1824747468305827), ([], Cell(1, 1), 2.1531854249492373), ([(4, 3, 1)], Cell(-99, -99), 1.2217514421272204), ([(5, 9, 2)], Cell(2, 2), 1.133363094478902), ([(8, 2, 2)], Cell(-99, -99), 1.233363094478902), ([(4, 7, 1), (4, 8, 1)], Cell(3, 3), 1.1169417382415925), ([(4, 9, 2)], Cell(-99, -99), 1.1169417382415925)]
