// Geometry parity tests — the Swift port is checked against numbers the
// Python reference engine actually produced (GeometryParity.swift is
// generated by engine/scripts/gen_swift_fixtures.py).
//
// Two comparison levels, per docs/PORT.md:
// - pure arithmetic (octile, projection): must be bit-exact (==)
// - libm-backed (trig, hypot): C libraries may differ by an ulp across
//   platforms, so 1e-12 relative tolerance
import Testing
@testable import NavCore

private func approx(_ a: Double, _ b: Double) -> Bool {
    a == b || abs(a - b) <= 1e-12 * max(1.0, abs(b))
}

private func approx(_ a: Vec, _ b: Vec) -> Bool {
    approx(a.x, b.x) && approx(a.y, b.y)
}

@Test func wrapAngleMatchesReference() {
    for (input, want) in wrapAngleCases {
        #expect(approx(wrapAngle(input), want), "wrapAngle(\(input))")
    }
}

@Test func bearingAndDistMatchReference() {
    for (a, b, wantBearing, wantDist) in bearingDistCases {
        #expect(approx(bearing(from: a, to: b), wantBearing))
        #expect(approx(dist(a, b), wantDist))
    }
}

@Test func octileIsBitExact() {
    for (a, b, want) in octileCases {
        #expect(octile(a, b) == want, "octile(\(a), \(b))")
    }
}

@Test func projectionIsBitExact() {
    for (p, a, b, wantPoint, wantT) in projectCases {
        let (got, t) = projectPointSegment(p, a, b)
        #expect(got == wantPoint && t == wantT, "project(\(p))")
    }
}

@Test func polylineWalkMatchesReference() {
    #expect(approx(polylineLength(polyline), polylineLen))
    #expect(polylineLength([]) == 0.0)
    #expect(polylineLength([Vec(1.0, 1.0)]) == 0.0)
    for (i, t, ahead, want) in pointAlongCases {
        #expect(approx(pointAlong(polyline, startI: i, startT: t,
                                  ahead: ahead), want))
    }
}

@Test func conventionSanity() {
    // positive bearing error = turn LEFT: a goal to the agent's left
    // (+y when facing +x) must yield a positive angle
    #expect(bearing(from: Vec(0.0, 0.0), to: Vec(1.0, 1.0)) > 0.0)
    // wrap stays in (-pi, pi]
    for a in stride(from: -20.0, through: 20.0, by: 0.37) {
        let w = wrapAngle(a)
        #expect(w > -3.14159266 && w <= 3.14159266)
    }
}
