// GENERATED by engine/scripts/gen_swift_fixtures.py — do not edit.
// Regenerate after any intentional change to the Python reference.
@testable import NavCore

let wpStream: [(String, String, Vec, Double, Int)] = [("report", "fridge", Vec(3.0, 2.0), 0.9, 1), ("report", "fridge", Vec(3.1, 2.05), 0.8, 2), ("report", "chair", Vec(1.0, 1.0), 0.6, 2), ("report", "fridge", Vec(2.95, 1.9), 1.0, 3), ("report", "ghost", Vec(5.0, 5.0), 0.4, 3), ("observe", "", Vec(3.0, 2.0), 2.6, 4), ("report", "chair", Vec(1.05, 0.95), 0.7, 5), ("observe", "", Vec(4.5, 4.5), 1.2, 6), ("observe", "", Vec(4.5, 4.5), 1.2, 7), ("report", "chair", Vec(1.0, 1.02), 0.9, 8), ("report", "chair", Vec(0.98, 1.0), 0.8, 9), ("observe", "", Vec(1.0, 1.0), 2.0, 10)]

let wpDeadLists: [[String]] = [["chair-1"], ["ghost-2"], [], []]

let wpFinal: [(String, String, Vec, Double, Int, Bool)] = [("chair-3", "chair", Vec(1.0079166666666663, 0.9929166666666666), 2.4000000000000004, 3, false), ("fridge-0", "fridge", Vec(3.011111111111111, 1.9777777777777776), 2.1, 3, true)]

let wpTargets: [String] = ["fridge-0"]

let snapStates: [Int] = [0, 12, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 2, 1, 0, 15, 1, 1, 0, 3, 2, 1, 0, 1, 1, 1, 0, 3, 1, 1, 0, 13, 1, 1, 0, 3, 2, 1, 0, 3, 1, 1, 0, 1, 1, 1, 0, 15, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 13, 1, 1, 0, 3, 1, 1, 0, 1, 2, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1]

let snapLabels: [(Int, String)] = [(12, "box"), (40, "box")]

let diffWant: [(Cell, Int, Int)] = [(Cell(0, 0), 0, 2), (Cell(3, 1), 0, 1)]

let diffAppeared = 1

let diffVanished = 0

let diffByLabel: [String: Int] = ["crate": 1]
