"""Generate Swift parity fixtures from the Python reference engine.

    python engine/scripts/gen_swift_fixtures.py

Writes apps/navcore/Tests/NavCoreTests/*Parity.swift: batteries of
(input, expected) pairs computed by the REFERENCE implementation, so the
Swift port is tested against the exact numbers Python produces — the
port contract of docs/PORT.md, mechanized. Python's repr() emits the
shortest decimal that round-trips the IEEE double, and Swift parses
literals to the nearest double, so values survive the trip bit-exact.

Pure-arithmetic functions must match to the last bit (== in Swift);
libm-backed ones (trig, hypot) may differ by an ulp across C libraries,
so their cases carry a 1e-12 relative tolerance instead.
"""

from __future__ import annotations

import math
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1] / "src"))

from theseus_engine import geometry as g  # noqa: E402
from theseus_engine.grid import OccupancyGrid, PlanParams  # noqa: E402

OUT = (pathlib.Path(__file__).resolve().parents[2]
       / "apps" / "navcore" / "Tests" / "NavCoreTests")

HEADER = """\
// GENERATED by engine/scripts/gen_swift_fixtures.py — do not edit.
// Regenerate after any intentional change to the Python reference.
@testable import NavCore
"""


def lit(x: float) -> str:
    """A Swift Double literal that parses to the same IEEE-754 value."""
    if x == math.inf:
        return "Double.infinity"
    if x == -math.inf:
        return "-Double.infinity"
    return repr(float(x))


def main() -> None:
    lines = [HEADER]

    angles = [-123.456, -10.0, -math.pi, -1.5, -1e-9, 0.0, 1e-9, 0.25,
              1.0, math.pi / 2, 3.0, math.pi, 3.5, 10.0, 123.456]
    cases = ", ".join(f"({lit(a)}, {lit(g.wrap_angle(a))})" for a in angles)
    lines.append(f"let wrapAngleCases: [(Double, Double)] = [{cases}]\n")

    vec_pairs = [((0.0, 0.0), (1.0, 0.0)), ((0.0, 0.0), (0.0, 1.0)),
                 ((1.0, 2.0), (-3.0, 5.0)), ((0.3, -0.7), (0.3, -0.7)),
                 ((-2.5, 4.0), (1.5, -1.0)), ((0.05, 0.05), (7.95, 5.95))]
    cases = ", ".join(
        f"(Vec({lit(a[0])}, {lit(a[1])}), Vec({lit(b[0])}, {lit(b[1])}), "
        f"{lit(g.bearing(a, b))}, {lit(g.dist(a, b))})"
        for a, b in vec_pairs)
    lines.append("let bearingDistCases: [(Vec, Vec, Double, Double)] = "
                 f"[{cases}]\n")

    cell_pairs = [((0, 0), (0, 0)), ((0, 0), (3, 4)), ((5, 1), (1, 5)),
                  ((-3, -7), (2, 9)), ((10, -2), (-4, -2)), ((1, 1), (2, 2))]
    cases = ", ".join(
        f"(Cell({a[0]}, {a[1]}), Cell({b[0]}, {b[1]}), {lit(g.octile(a, b))})"
        for a, b in cell_pairs)
    lines.append(f"let octileCases: [(Cell, Cell, Double)] = [{cases}]\n")

    proj = [((1.0, 1.0), (0.0, 0.0), (2.0, 0.0)),
            ((-1.0, 0.5), (0.0, 0.0), (2.0, 0.0)),
            ((5.0, 5.0), (0.0, 0.0), (2.0, 0.0)),
            ((1.0, 1.0), (3.0, 3.0), (3.0, 3.0)),
            ((0.7, -0.2), (-1.0, -1.0), (2.0, 0.5))]
    cases = ", ".join(
        f"(Vec({lit(p[0])}, {lit(p[1])}), Vec({lit(a[0])}, {lit(a[1])}), "
        f"Vec({lit(b[0])}, {lit(b[1])}), "
        f"Vec({lit(g.project_point_segment(p, a, b)[0][0])}, "
        f"{lit(g.project_point_segment(p, a, b)[0][1])}), "
        f"{lit(g.project_point_segment(p, a, b)[1])})"
        for p, a, b in proj)
    lines.append("let projectCases: [(Vec, Vec, Vec, Vec, Double)] = "
                 f"[{cases}]\n")

    poly = [(0.0, 0.0), (1.0, 0.0), (1.0, 2.0), (-0.5, 2.0), (-0.5, -1.0)]
    lines.append(f"let polyline: [Vec] = ["
                 + ", ".join(f"Vec({lit(x)}, {lit(y)})" for x, y in poly)
                 + "]")
    lines.append(f"let polylineLen: Double = {lit(g.polyline_length(poly))}\n")

    walks = [(0, 0.0, 0.5), (0, 0.0, 2.7), (1, 0.5, 0.1), (0, 0.9, 10.0),
             (2, 0.0, 0.0), (3, 0.25, 99.0)]
    cases = ", ".join(
        f"({i}, {lit(t)}, {lit(ah)}, "
        f"Vec({lit(g.point_along(poly, i, t, ah)[0])}, "
        f"{lit(g.point_along(poly, i, t, ah)[1])}))"
        for i, t, ah in walks)
    lines.append("let pointAlongCases: [(Int, Double, Double, Vec)] = "
                 f"[{cases}]\n")

    OUT.mkdir(parents=True, exist_ok=True)
    path = OUT / "GeometryParity.swift"
    path.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"wrote {path}")
    gen_grid()


def _built_grid():
    """The shared scripted grid: a fixed pseudo-random observation
    sequence, so every parity battery (grid, astar, ...) exercises the
    same world."""
    grid = OccupancyGrid(12, 10, 0.05, origin=(-0.3, -0.2))
    grid.clearance_cap = 1.2
    ops = []
    s = 12345
    for k in range(240):
        s = (s * 1103515245 + 12345) % (1 << 31)
        x = s % 12
        s = (s * 1103515245 + 12345) % (1 << 31)
        y = s % 10
        occ = (s >> 7) % 4 == 0
        label = "box" if occ and k % 17 == 0 else ""
        ops.append((x, y, occ, k, label))
    changed = [grid.observe((x, y), o, tick=t, label=lab)
               for x, y, o, t, lab in ops]
    return grid, ops, changed


def gen_grid() -> None:
    """Grid parity: a deterministic observation script plus every derived
    number (states, clearance, costs). Grid math is libm-free, so ALL of
    these must match bit-for-bit in Swift — comparisons are ==, no
    tolerance."""
    grid, ops, changed = _built_grid()
    params = PlanParams(radius=0.05, safe_margin=0.15, margin_weight=1.5)

    cells = [(x, y) for y in range(10) for x in range(12)]
    states = "".join(str(grid.state(c)) for c in cells)
    clear = ", ".join(lit(grid.clearance(c)) for c in cells)
    costs = ", ".join(lit(grid.cell_cost(c, params)) for c in cells)

    edge_pairs = [((1, 1), (2, 1)), ((1, 1), (2, 2)), ((5, 5), (5, 6)),
                  ((5, 5), (6, 6)), ((0, 0), (-1, 0)), ((11, 9), (11, 8)),
                  ((3, 7), (4, 8)), ((8, 2), (7, 1)), ((6, 4), (6, 3)),
                  ((2, 8), (3, 8)), ((9, 6), (10, 7)), ((4, 3), (3, 4))]
    edges = ", ".join(
        f"(Cell({a[0]}, {a[1]}), Cell({b[0]}, {b[1]}), "
        f"{lit(grid.edge_cost(a, b, params))})" for a, b in edge_pairs)

    w2c = [(-0.3, -0.2), (-0.301, -0.201), (0.0, 0.0), (-0.25, -0.15),
           (0.299, 0.299), (-0.5, 0.3), (0.3, -0.4)]
    w2c_cases = ", ".join(
        f"(Vec({lit(p[0])}, {lit(p[1])}), "
        f"Cell({grid.world_to_cell(p)[0]}, {grid.world_to_cell(p)[1]}))"
        for p in w2c)

    fm = [(0.425, 0.475, 0.05), (0.375, 0.325, 0.05), (8.0, 6.0, 0.05),
          (1.25, 0.75, 0.1)]
    fm_cases = ", ".join(
        f"({lit(w)}, {lit(h)}, {lit(c)}, "
        f"{OccupancyGrid.from_meters(w, h, c).width}, "
        f"{OccupancyGrid.from_meters(w, h, c).height})" for w, h, c in fm)

    mca = [((-0.25, -0.15), (0.2, 0.25)), ((0.0, 0.0), (0.25, -0.1))]
    mca_cases = ", ".join(
        f"(Vec({lit(a[0])}, {lit(a[1])}), Vec({lit(b[0])}, {lit(b[1])}), "
        f"{lit(grid.min_clearance_along(a, b))})" for a, b in mca)

    labeled = sorted((i, lab) for i, lab in grid.labels.items())
    label_cases = ", ".join(f"({i}, \"{lab}\")" for i, lab in labeled)

    lines = [
        HEADER,
        "let gridOps: [(Int32, Int32, Bool, Int, String)] = ["
        + ", ".join(f"({x}, {y}, {str(o).lower()}, {t}, \"{lab}\")"
                    for x, y, o, t, lab in ops) + "]\n",
        "let gridChanged: [Bool] = ["
        + ", ".join(str(c).lower() for c in changed) + "]\n",
        f"let gridStates = \"{states}\"\n",
        f"let gridClearance: [Double] = [{clear}]\n",
        f"let gridCellCosts: [Double] = [{costs}]\n",
        f"let gridEdgeCases: [(Cell, Cell, Double)] = [{edges}]\n",
        f"let worldToCellCases: [(Vec, Cell)] = [{w2c_cases}]\n",
        "let fromMetersCases: [(Double, Double, Double, Int, Int)] = "
        f"[{fm_cases}]\n",
        f"let minClearanceCases: [(Vec, Vec, Double)] = [{mca_cases}]\n",
        f"let gridLabels: [(Int, String)] = [{label_cases}]\n",
    ]
    path = OUT / "GridParity.swift"
    path.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"wrote {path}")
    gen_astar()


def _cell(c) -> str:
    return f"Cell({c[0]}, {c[1]})"


def _vec(p) -> str:
    return f"Vec({lit(p[0])}, {lit(p[1])})"


def _nav_ops():
    """Observation script for a NAVIGABLE world (the messy grid parity
    world is 80% unknown — fine for cost parity, useless for routing):
    carve everything free (twice — log-odds needs two misses to cross
    the FREE threshold), then two walls with offset gaps, forcing an
    S-shaped route corner to corner."""
    ops = []
    for _ in range(2):
        for y in range(10):
            for x in range(12):
                ops.append((x, y, False))
    walls = ([(4, y) for y in range(0, 7)]        # gap at the top
             + [(8, y) for y in range(3, 10)]     # gap at the bottom
             + [(1, 5), (2, 5)])
    # three hits: the free carving drove these to log-odds -1.2, and
    # crossing the OCCUPIED threshold (+0.7) needs +0.85 * 3 from there
    for _ in range(3):
        for c in walls:
            ops.append((c[0], c[1], True))
    return ops


def gen_astar() -> None:
    """A* parity: full planned paths (exact cell sequences — identical
    tie-breaking makes them deterministic), costs, the Dijkstra oracle
    agreement, smoothing output and corridor checks."""
    from theseus_engine import astar

    grid = OccupancyGrid(12, 10, 0.05, origin=(-0.3, -0.2))
    grid.clearance_cap = 1.2
    nav_ops = _nav_ops()
    for x, y, occ in nav_ops:
        grid.observe((x, y), occ)
    params = PlanParams(radius=0.05, safe_margin=0.15, margin_weight=1.5)

    pair_picks = [((0, 0), (11, 9)), ((0, 9), (11, 0)), ((0, 0), (11, 0)),
                  ((2, 2), (2, 8)), ((6, 1), (6, 8)), ((3, 3), (3, 3))]
    plan_cases, smooth_cases = [], []
    for start, goal in pair_picks:
        res = astar.plan(grid, start, goal, params)
        assert res is not None, f"nav grid should connect {start}->{goal}"
        dij = astar.plan(grid, start, goal, params, use_heuristic=False)
        assert dij is not None and abs(dij.cost - res.cost) < 1e-9, \
            f"A* not optimal for {start}->{goal}?!"
        cells = "[" + ", ".join(_cell(c) for c in res.cells) + "]"
        plan_cases.append(f"({_cell(start)}, {_cell(goal)}, {cells}, "
                          f"{lit(res.cost)})")
        sm = astar.smooth(grid, res.cells, params)
        smooth_cases.append("[" + ", ".join(_vec(p) for p in sm) + "]")

    occ_cells = [(x, y) for y in range(10) for x in range(12)
                 if grid.state((x, y)) == 2]
    unreachable = [((0, 0), occ_cells[0]), (occ_cells[0], (0, 0)),
                   ((-1, 0), (0, 0))]
    unreach = ", ".join(f"({_cell(a)}, {_cell(b)})" for a, b in unreachable)

    corr = [((-0.25, -0.15), (0.2, 0.25)), ((-0.28, -0.18), (-0.1, 0.0)),
            ((0.0, 0.0), (0.25, 0.28)), ((-0.2, 0.1), (0.15, 0.1))]
    corr_cases = ", ".join(
        f"({_vec(a)}, {_vec(b)}, "
        f"{str(astar.corridor_clear(grid, a, b, params)).lower()})"
        for a, b in corr)

    bad = [(0, 0), occ_cells[0]]
    nav_ops_lit = ", ".join(f"({x}, {y}, {str(o).lower()})"
                            for x, y, o in nav_ops)
    lines = [
        HEADER,
        f"let navOps: [(Int32, Int32, Bool)] = [{nav_ops_lit}]\n",
        "let planCases: [(Cell, Cell, [Cell], Double)] = ["
        + ", ".join(plan_cases) + "]\n",
        "let smoothCases: [[Vec]] = [" + ", ".join(smooth_cases) + "]\n",
        f"let unreachableCases: [(Cell, Cell)] = [{unreach}]\n",
        f"let corridorCases: [(Vec, Vec, Bool)] = [{corr_cases}]\n",
        "let badPath: [Cell] = ["
        + ", ".join(_cell(c) for c in bad) + "]\n",
    ]
    path = OUT / "AstarParity.swift"
    path.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"wrote {path}")
    gen_fsm()


def gen_fsm() -> None:
    """FSM parity: exhaustive (state, event) enumeration — can() plus the
    resulting state for every legal pair — and one long scripted journey
    that exercises the tracking-lost resume path."""
    from theseus_engine.fsm import Event, State, StateMachine

    combos = []
    for s in State:
        for e in Event:
            m = StateMachine(initial=s)
            ok = m.can(e)
            nxt = ""
            if ok:
                nxt = m.step(e).value
            combos.append(f"(\"{s.value}\", \"{e.value}\", "
                          f"{str(ok).lower()}, \"{nxt}\")")

    journey = [Event.SCAN_STARTED, Event.TRACKING_LOST,
               Event.TRACKING_RECOVERED, Event.GOAL_SET, Event.PLAN_READY,
               Event.OFF_ROUTE, Event.PLAN_FAILED, Event.RETRY,
               Event.PLAN_READY, Event.ARRIVED_EVT, Event.WALK_TOGGLED,
               Event.TRACKING_LOST, Event.TRACKING_RECOVERED,
               Event.WALK_TOGGLED]
    m = StateMachine()
    script = ", ".join(f"(\"{e.value}\", \"{m.step(e).value}\")"
                       for e in journey)

    lines = [
        HEADER,
        "let fsmCombos: [(String, String, Bool, String)] = ["
        + ", ".join(combos) + "]\n",
        f"let fsmJourney: [(String, String)] = [{script}]\n",
    ]
    path = OUT / "FsmParity.swift"
    path.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"wrote {path}")
    gen_dstar()


def gen_dstar() -> None:
    """D* Lite parity: a scripted scenario of world edits and agent moves
    on the navigable grid. After every step the incremental planner's
    cost must equal a fresh A* plan (asserted here, re-checked in Swift
    against the SWIFT A* — the equivalence property, cross-language)."""
    from theseus_engine import astar
    from theseus_engine.dstar_lite import DStarLite
    import math as m

    grid = OccupancyGrid(12, 10, 0.05, origin=(-0.3, -0.2))
    grid.clearance_cap = 1.2
    for x, y, occ in _nav_ops():
        grid.observe((x, y), occ)
    params = PlanParams(radius=0.05, safe_margin=0.15, margin_weight=1.5)
    start, goal = (0, 0), (11, 9)
    ds = DStarLite(grid, start, goal, params)

    # (cell writes as (x, y, state), move-start-to or None)
    script = [
        ([], None),                          # initial plan
        ([(4, 7, 2), (4, 8, 2)], None),      # top gap narrows to one row
        ([], (1, 1)),                        # agent advances
        ([(4, 3, 1)], None),                 # hole punched mid-wall
        ([(5, 9, 2)], (2, 2)),               # clutter appears; agent moves
        ([(8, 2, 2)], None),                 # bottom gap narrows
        ([(4, 7, 1), (4, 8, 1)], (3, 3)),    # top gap reopens; agent moves
        ([(4, 9, 2)], None),                 # top gap CLOSES entirely
    ]
    steps = []
    for writes, move in script:
        changed = []
        for x, y, st in writes:
            grid.set_state((x, y), st)
            changed.append((x, y))
        if changed:
            ds.notify_changed(changed)
        if move is not None:
            ds.update_start(move)
        res = ds.plan()
        ref = astar.plan(grid, ds.start, goal, params)
        if res is None:
            assert ref is None, f"D* None but A* found a path: {writes}"
            want = INF
        else:
            assert ref is not None and abs(res.cost - ref.cost) < 1e-9, \
                f"D* != A* after {writes}: {res.cost} vs {ref and ref.cost}"
            want = res.cost
        mv = move if move is not None else (-99, -99)
        w = "[" + ", ".join(f"({x}, {y}, {st})" for x, y, st in writes) + "]"
        steps.append(f"({w}, {_cell(mv)}, {lit(want)})")

    lines = [
        HEADER,
        "let dstarSteps: [([(Int32, Int32, Int)], Cell, Double)] = ["
        + ", ".join(steps) + "]\n",
    ]
    path = OUT / "DstarParity.swift"
    path.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"wrote {path}")
    gen_flowfield()


def gen_flowfield() -> None:
    """Flow-field parity on the navigable grid: the full single-goal
    distance field (bit-exact — heap tie-breaks are fully ordered), a
    multi-goal sample, and greedy-descent routes."""
    from theseus_engine.flowfield import FlowField

    grid = OccupancyGrid(12, 10, 0.05, origin=(-0.3, -0.2))
    grid.clearance_cap = 1.2
    for x, y, occ in _nav_ops():
        grid.observe((x, y), occ)
    params = PlanParams(radius=0.05, safe_margin=0.15, margin_weight=1.5)

    ff = FlowField.build(grid, [(11, 9)], params)
    dist_a = ", ".join(lit(ff.distance((x, y)))
                       for y in range(10) for x in range(12))

    ffb = FlowField.build(grid, [(0, 0), (11, 0)], params)
    dist_b = ", ".join(lit(ffb.distance((x, y)))
                       for y in range(10) for x in range(12))

    routes = []
    for s in [(0, 0), (0, 9), (6, 1)]:
        r = ff.route_from(s)
        assert r is not None
        cells = "[" + ", ".join(_cell(c) for c in r.cells) + "]"
        routes.append(f"({_cell(s)}, {cells}, {lit(r.cost)})")

    lines = [
        HEADER,
        f"let ffDistSingle: [Double] = [{dist_a}]\n",
        f"let ffDistMulti: [Double] = [{dist_b}]\n",
        "let ffRoutes: [(Cell, [Cell], Double)] = ["
        + ", ".join(routes) + "]\n",
    ]
    path = OUT / "FlowFieldParity.swift"
    path.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"wrote {path}")
    gen_solvers()


def _partial_ops():
    """A half-explored world for frontier tests: left side carved free,
    a wall with a gap at the top, right side never observed."""
    ops = []
    for _ in range(2):
        for y in range(10):
            for x in range(6):
                ops.append((x, y, False))
    for _ in range(3):
        for y in range(8):
            ops.append((4, y, True))
    return ops


def gen_solvers() -> None:
    """Frontier / coverage / queries parity on their natural worlds."""
    from theseus_engine import frontier
    from theseus_engine.coverage import coverage_fraction, coverage_route
    from theseus_engine.queries import (corridor_profile, fits_through,
                                        nearest_semantic)

    params = PlanParams(radius=0.05, safe_margin=0.15, margin_weight=1.5)

    # --- frontier on the partial world --------------------------------
    pgrid = OccupancyGrid(12, 10, 0.05, origin=(-0.3, -0.2))
    pgrid.clearance_cap = 1.2
    partial = _partial_ops()
    for x, y, occ in partial:
        pgrid.observe((x, y), occ)
    fcells = frontier.frontier_cells(pgrid)
    fclusters = frontier.clusters(fcells, 3)
    t0 = frontier.select_target(pgrid, (0, 0), params)
    t1 = frontier.select_target(pgrid, (0, 0), params, min_dist_m=0.3)
    assert t0 is not None and t1 is not None

    def tgt(t):
        return f"({_cell(t.cell)}, {t.cluster_size}, {lit(t.travel_cost)})"

    partial_lit = ", ".join(f"({x}, {y}, {str(o).lower()})"
                            for x, y, o in partial)
    fcells_lit = ", ".join(_cell(c) for c in fcells)
    fclusters_lit = ", ".join(
        "[" + ", ".join(_cell(c) for c in comp) + "]" for comp in fclusters)

    # --- coverage on the navigable world ------------------------------
    ngrid = OccupancyGrid(12, 10, 0.05, origin=(-0.3, -0.2))
    ngrid.clearance_cap = 1.2
    for x, y, occ in _nav_ops():
        ngrid.observe((x, y), occ)
    cov = coverage_route(ngrid, (0, 0), params, lane_width=0.2)
    assert cov is not None
    frac = coverage_fraction(ngrid, cov.cells, params, lane_width=0.2)
    visit_lit = ", ".join(_cell(c) for c in cov.visit_points)

    # --- queries on the navigable world + labels ----------------------
    ngrid.set_state((10, 1), 2, label="fridge")
    ngrid.set_state((1, 8), 2, label="couch")
    routes = []
    for lab in ("fridge", "couch"):
        r = nearest_semantic(ngrid, (0, 0), lab, params, approach_m=0.2)
        assert r is not None, f"no route to {lab}"
        cells = "[" + ", ".join(_cell(c) for c in r.cells) + "]"
        routes.append(f"(\"{lab}\", {cells}, {lit(r.cost)})")
    assert nearest_semantic(ngrid, (0, 0), "ghost", params) is None

    pts = [(-0.25, -0.15), (0.1, 0.0), (0.25, 0.25)]
    prof = corridor_profile(ngrid, pts)
    prof_lit = ", ".join(f"({lit(s)}, {lit(w)})" for s, w in prof)
    fits = []
    for w in (0.1, 0.5):
        ok, pinch, narrow = fits_through(ngrid, pts, w)
        p = _vec(pinch) if pinch is not None else "Vec(-99.0, -99.0)"
        fits.append(f"({lit(w)}, {str(ok).lower()}, {p}, {lit(narrow)})")
    pts_lit = ", ".join(_vec(p) for p in pts)

    lines = [
        HEADER,
        f"let partialOps: [(Int32, Int32, Bool)] = [{partial_lit}]\n",
        f"let frontierCellsWant: [Cell] = [{fcells_lit}]\n",
        f"let frontierClustersWant: [[Cell]] = [{fclusters_lit}]\n",
        f"let frontierTarget0: (Cell, Int, Double) = {tgt(t0)}\n",
        f"let frontierTargetMinDist: (Cell, Int, Double) = {tgt(t1)}\n",
        f"let coverageVisit: [Cell] = [{visit_lit}]\n",
        f"let coverageLanes = {cov.lanes}\n",
        f"let coverageSkipped = {cov.skipped}\n",
        f"let coverageCellCount = {len(cov.cells)}\n",
        f"let coverageFrac: Double = {lit(frac)}\n",
        "let semanticRoutes: [(String, [Cell], Double)] = ["
        + ", ".join(routes) + "]\n",
        f"let profilePts: [Vec] = [{pts_lit}]\n",
        f"let profileWant: [(Double, Double)] = [{prof_lit}]\n",
        "let fitsCases: [(Double, Bool, Vec, Double)] = ["
        + ", ".join(fits) + "]\n",
    ]
    path = OUT / "SolverParity.swift"
    path.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"wrote {path}")
    gen_state()


def gen_state() -> None:
    """Waypoint-registry and snapshot parity: a scripted detection
    stream with merges, promotions, and decay deaths; RLE round-trip and
    diff on the messy grid."""
    from theseus_engine import serialize
    from theseus_engine.waypoints import WaypointRegistry

    reg = WaypointRegistry()
    stream = [
        ("report", "fridge", (3.0, 2.0), 0.9, 1),
        ("report", "fridge", (3.1, 2.05), 0.8, 2),
        ("report", "chair", (1.0, 1.0), 0.6, 2),
        ("report", "fridge", (2.95, 1.9), 1.0, 3),
        ("report", "ghost", (5.0, 5.0), 0.4, 3),
        ("observe", (3.0, 2.0), 2.6, 4),
        ("report", "chair", (1.05, 0.95), 0.7, 5),
        ("observe", (4.5, 4.5), 1.2, 6),
        ("observe", (4.5, 4.5), 1.2, 7),
        ("report", "chair", (1.0, 1.02), 0.9, 8),
        ("report", "chair", (0.98, 1.0), 0.8, 9),
        ("observe", (1.0, 1.0), 2.0, 10),
    ]
    ops_lit, deads = [], []
    for op in stream:
        if op[0] == "report":
            _, lab, pos, conf, tick = op
            wp = reg.report(lab, pos, confidence=conf, tick=tick)
            ops_lit.append(f"(\"report\", \"{lab}\", {_vec(pos)}, "
                           f"{lit(conf)}, {tick})")
        else:
            _, center, radius, tick = op
            seen = set()
            if tick == 10:  # the chair was re-sighted this frame
                seen = {w.uid for w in reg.all() if w.label == "chair"}
            dead = reg.observe_area(center, radius, tick, seen)
            deads.append(dead)
            ops_lit.append(f"(\"observe\", {_vec(center)}, {lit(radius)}, "
                           f"{tick})")
    final = ", ".join(
        f"(\"{w.uid}\", \"{w.label}\", {_vec(w.pos)}, {lit(w.confidence)}, "
        f"{w.hits}, {str(w.promoted).lower()})" for w in reg.all())
    targets = ", ".join(f"\"{w.uid}\"" for w in reg.targets())
    deads_lit = ", ".join(
        "[" + ", ".join(f"\"{u}\"" for u in d) + "]" for d in deads)

    # --- snapshot round-trip + diff on the messy grid ------------------
    grid, _, _ = _built_grid()
    snap = serialize.to_dict(grid)
    grid2, _, _ = _built_grid()
    grid2.set_state((0, 0), 2, label="crate")   # appeared
    grid2.set_state((3, 1), 1)                  # whatever it was -> free
    d = serialize.diff(grid, grid2)
    rep = serialize.diff_report(grid, grid2)
    states_lit = ", ".join(str(v) for v in snap["states"])
    labels_lit = ", ".join(f"({k}, \"{v}\")"
                           for k, v in sorted(grid.labels.items()))
    diff_lit = ", ".join(f"({_cell(c)}, {sa}, {sb})" for c, sa, sb in d)
    by_label = ", ".join(f"\"{k}\": {v}"
                         for k, v in sorted(rep["by_label"].items()))

    lines = [
        HEADER,
        "let wpStream: [(String, String, Vec, Double, Int)] = ["
        + ", ".join(o if o.startswith("(\"report")
                    else o.replace("(\"observe\", ", "(\"observe\", \"\", ")
                    for o in ops_lit) + "]\n",
        f"let wpDeadLists: [[String]] = [{deads_lit}]\n",
        "let wpFinal: [(String, String, Vec, Double, Int, Bool)] = ["
        + final + "]\n",
        f"let wpTargets: [String] = [{targets}]\n",
        f"let snapStates: [Int] = [{states_lit}]\n",
        f"let snapLabels: [(Int, String)] = [{labels_lit}]\n",
        f"let diffWant: [(Cell, Int, Int)] = [{diff_lit}]\n",
        f"let diffAppeared = {rep['appeared']}\n",
        f"let diffVanished = {rep['vanished']}\n",
        f"let diffByLabel: [String: Int] = [{by_label or ':'}]\n",
    ]
    path = OUT / "StateParity.swift"
    path.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"wrote {path}")
    gen_motion()


def gen_motion() -> None:
    """Steering + guidance parity: scripted decide() calls (hysteresis
    state carried across the sequence) and cue() probes covering every
    cue kind — the turn-sign cases are the point."""
    import math as m

    from theseus_engine import astar
    from theseus_engine.guidance import GuidanceFollower
    from theseus_engine.steering import VFHSteering

    grid = OccupancyGrid(12, 10, 0.05, origin=(-0.3, -0.2))
    grid.clearance_cap = 1.2
    for x, y, occ in _nav_ops():
        grid.observe((x, y), occ)
    params = PlanParams(radius=0.05, safe_margin=0.15, margin_weight=1.5)

    steer = VFHSteering(params, lookahead=0.4, min_free=0.1)
    poses = [
        ((-0.15, -0.1, 0.3), 0.5),
        ((-0.13, -0.08, 0.3), 0.5),
        ((-0.11, -0.06, 0.35), 0.6),
        ((-0.09, -0.04, 0.4), None),
        ((-0.05, 0.0, 0.4), 1.2),
        ((0.0, 0.05, 0.5), 1.2),
    ]
    decisions = []
    for pose, gb in poses:
        d = steer.decide(grid, pose, gb)
        gb_lit = lit(gb) if gb is not None else "-99.0"
        decisions.append(
            f"({_vec(pose[:2])}, {lit(pose[2])}, {gb_lit}, "
            f"{lit(d.heading)}, {lit(d.speed)}, {lit(d.free_dist)}, "
            f"{str(d.blocked).lower()}, \"{d.reason}\")")

    plan_res = astar.plan(grid, (0, 0), (11, 9), params)
    smoothed = astar.smooth(grid, plan_res.cells, params)
    gf = GuidanceFollower(smoothed)
    probe_poses = [
        (-0.275, -0.175, 0.6),      # near start, roughly on-heading
        (-0.275, -0.175, -1.2),     # same spot, facing right of path
        (-0.275, -0.175, 2.6),      # facing left of path
        (-0.1, 0.05, 0.8),          # mid-path
        (smoothed[-1][0] - 0.02, smoothed[-1][1] - 0.02, 0.0),  # at goal
        (-0.28, 1.5, 0.0),          # way off in the weeds
    ]
    cues = []
    for pose in probe_poses:
        c = gf.cue(grid, pose)
        cues.append(
            f"({_vec(pose[:2])}, {lit(pose[2])}, \"{c.kind}\", "
            f"{lit(c.distance)}, {lit(c.angle_deg)}, {lit(c.cross_track)}, "
            f"{lit(c.corridor)}, {_vec(c.target)})")
    kinds = {c.split('\"')[1] for c in [x for x in cues]}

    smoothed_lit = ", ".join(_vec(p) for p in smoothed)
    lines = [
        HEADER,
        "let steerScript: "
        "[(Vec, Double, Double, Double, Double, Double, Bool, String)] = ["
        + ", ".join(decisions) + "]\n",
        f"let guidePath: [Vec] = [{smoothed_lit}]\n",
        "let cueProbes: "
        "[(Vec, Double, String, Double, Double, Double, Double, Vec)] = ["
        + ", ".join(cues) + "]\n",
    ]
    path = OUT / "MotionParity.swift"
    path.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"wrote {path}")


if __name__ == "__main__":
    main()
