"""Generate Swift parity fixtures from the Python reference engine.

    python engine/scripts/gen_swift_fixtures.py

Writes apps/navcore/Tests/NavCoreTests/*Parity.swift: batteries of
(input, expected) pairs computed by the REFERENCE implementation, so the
Swift port is tested against the exact numbers Python produces — the
port contract of docs/PORT.md, mechanized. Python's repr() emits the
shortest decimal that round-trips the IEEE double, and Swift parses
literals to the nearest double, so values survive the trip bit-exact.

Pure-arithmetic functions must match to the last bit (== in Swift);
libm-backed ones (trig, hypot) may differ by an ulp across C libraries,
so their cases carry a 1e-12 relative tolerance instead.
"""

from __future__ import annotations

import math
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1] / "src"))

from theseus_engine import geometry as g  # noqa: E402

OUT = (pathlib.Path(__file__).resolve().parents[2]
       / "apps" / "navcore" / "Tests" / "NavCoreTests")

HEADER = """\
// GENERATED by engine/scripts/gen_swift_fixtures.py — do not edit.
// Regenerate after any intentional change to the Python reference.
@testable import NavCore
"""


def lit(x: float) -> str:
    """A Swift Double literal that parses to the same IEEE-754 value."""
    if x == math.inf:
        return "Double.infinity"
    if x == -math.inf:
        return "-Double.infinity"
    return repr(float(x))


def main() -> None:
    lines = [HEADER]

    angles = [-123.456, -10.0, -math.pi, -1.5, -1e-9, 0.0, 1e-9, 0.25,
              1.0, math.pi / 2, 3.0, math.pi, 3.5, 10.0, 123.456]
    cases = ", ".join(f"({lit(a)}, {lit(g.wrap_angle(a))})" for a in angles)
    lines.append(f"let wrapAngleCases: [(Double, Double)] = [{cases}]\n")

    vec_pairs = [((0.0, 0.0), (1.0, 0.0)), ((0.0, 0.0), (0.0, 1.0)),
                 ((1.0, 2.0), (-3.0, 5.0)), ((0.3, -0.7), (0.3, -0.7)),
                 ((-2.5, 4.0), (1.5, -1.0)), ((0.05, 0.05), (7.95, 5.95))]
    cases = ", ".join(
        f"(Vec({lit(a[0])}, {lit(a[1])}), Vec({lit(b[0])}, {lit(b[1])}), "
        f"{lit(g.bearing(a, b))}, {lit(g.dist(a, b))})"
        for a, b in vec_pairs)
    lines.append("let bearingDistCases: [(Vec, Vec, Double, Double)] = "
                 f"[{cases}]\n")

    cell_pairs = [((0, 0), (0, 0)), ((0, 0), (3, 4)), ((5, 1), (1, 5)),
                  ((-3, -7), (2, 9)), ((10, -2), (-4, -2)), ((1, 1), (2, 2))]
    cases = ", ".join(
        f"(Cell({a[0]}, {a[1]}), Cell({b[0]}, {b[1]}), {lit(g.octile(a, b))})"
        for a, b in cell_pairs)
    lines.append(f"let octileCases: [(Cell, Cell, Double)] = [{cases}]\n")

    proj = [((1.0, 1.0), (0.0, 0.0), (2.0, 0.0)),
            ((-1.0, 0.5), (0.0, 0.0), (2.0, 0.0)),
            ((5.0, 5.0), (0.0, 0.0), (2.0, 0.0)),
            ((1.0, 1.0), (3.0, 3.0), (3.0, 3.0)),
            ((0.7, -0.2), (-1.0, -1.0), (2.0, 0.5))]
    cases = ", ".join(
        f"(Vec({lit(p[0])}, {lit(p[1])}), Vec({lit(a[0])}, {lit(a[1])}), "
        f"Vec({lit(b[0])}, {lit(b[1])}), "
        f"Vec({lit(g.project_point_segment(p, a, b)[0][0])}, "
        f"{lit(g.project_point_segment(p, a, b)[0][1])}), "
        f"{lit(g.project_point_segment(p, a, b)[1])})"
        for p, a, b in proj)
    lines.append("let projectCases: [(Vec, Vec, Vec, Vec, Double)] = "
                 f"[{cases}]\n")

    poly = [(0.0, 0.0), (1.0, 0.0), (1.0, 2.0), (-0.5, 2.0), (-0.5, -1.0)]
    lines.append(f"let polyline: [Vec] = ["
                 + ", ".join(f"Vec({lit(x)}, {lit(y)})" for x, y in poly)
                 + "]")
    lines.append(f"let polylineLen: Double = {lit(g.polyline_length(poly))}\n")

    walks = [(0, 0.0, 0.5), (0, 0.0, 2.7), (1, 0.5, 0.1), (0, 0.9, 10.0),
             (2, 0.0, 0.0), (3, 0.25, 99.0)]
    cases = ", ".join(
        f"({i}, {lit(t)}, {lit(ah)}, "
        f"Vec({lit(g.point_along(poly, i, t, ah)[0])}, "
        f"{lit(g.point_along(poly, i, t, ah)[1])}))"
        for i, t, ah in walks)
    lines.append("let pointAlongCases: [(Int, Double, Double, Vec)] = "
                 f"[{cases}]\n")

    OUT.mkdir(parents=True, exist_ok=True)
    path = OUT / "GeometryParity.swift"
    path.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"wrote {path}")


if __name__ == "__main__":
    main()
